openapi: 3.0.0
info:
  title: Employex
  description: "This is a sample API that allows to manage Employex system, which\
    \ serves for users seeking to apply for job offers.\n"
  contact:
    name: Ricardo Ru√≠z
    url: https://twitter.com/ricardordars
    email: ricardorzan@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ricardorzan/Employex/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/Employex/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://employex.swagger.io/v2
tags:
- name: general_user
  description: Operations about general user
- name: independient_user
  description: Operations about independient user
- name: organization_user
  description: Operations about organization user
- name: job_offer
  description: Everything about jobs offer
- name: aplications
  description: Everything about aplications
- name: education
  description: Everything about education section of independients users
- name: laboral_experience
  description: Everything about laboral experience section of independients users
- name: certification
  description: Everything about cerrification section of independients users
- name: section
  description: Everything about especial section of independients users
paths:
  /users/login:
    get:
      tags:
      - general_user
      summary: Logs user into the system
      operationId: login_user
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: email
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: password
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Invalid username/password supplied
      x-openapi-router-controller: swagger_server.controllers.general_user_controller
  /users/logout:
    get:
      tags:
      - general_user
      summary: Logs out current logged in user session
      operationId: logout_user
      responses:
        default:
          description: successful operation
      x-openapi-router-controller: swagger_server.controllers.general_user_controller
  /users/validation:
    patch:
      tags:
      - general_user
      summary: The user is validated so he can enter in the aplication
      operationId: validate_user
      parameters:
      - name: username
        in: query
        description: The user name for vaidation
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: email
      - name: token
        in: query
        description: The token for te account validation
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: succesful operation
      x-openapi-router-controller: swagger_server.controllers.general_user_controller
  /users/new_token:
    patch:
      tags:
      - general_user
      summary: The user generates a new validation token
      operationId: generate_new_token
      parameters:
      - name: username
        in: query
        description: The user name who generates the new token
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: eamil
      - name: fullName
        in: query
        description: The independient or organization user full name
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: succesful operation
      x-openapi-router-controller: swagger_server.controllers.general_user_controller
  /users/independient_user:
    post:
      tags:
      - independient_user
      summary: Register independient user
      operationId: register_indpendient_user
      requestBody:
        description: Independient user object to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndependientUser'
        required: true
      responses:
        default:
          description: successful operation
      x-openapi-router-controller: swagger_server.controllers.independient_user_controller
  /users/independient_user/{user_id}:
    get:
      tags:
      - independient_user
      summary: Get user by user id
      operationId: get_independint_user_by_id
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndependientUser'
        "400":
          description: Invalid username supplied
        "401":
          description: Access token is missing or invalid
        "404":
          description: User not found
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.independient_user_controller
    patch:
      tags:
      - independient_user
      summary: Patch user by id
      operationId: patch_independint_user_by_id
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Independient user object to patch
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndependientUser'
        required: true
      responses:
        default:
          description: succesful operations.independient_user_controller
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.independient_user_controller
  /users/independient_user/{user_id}/education:
    post:
      tags:
      - education
      summary: Adds education info to an independient user
      operationId: add_education
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      requestBody:
        $ref: '#/components/requestBodies/Education'
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.education_controller
  /users/independient_user/{user_id}/laboral_experience:
    post:
      tags:
      - laboral_experience
      summary: Adds laboral experience info to an independient user
      operationId: add_laboral_experience
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      requestBody:
        $ref: '#/components/requestBodies/LaboralExperience'
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.laboral_experience_controller
  /users/independient_user/{user_id}/certification:
    post:
      tags:
      - certification
      summary: Adds certification info to an independient user
      operationId: add_certification
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      requestBody:
        $ref: '#/components/requestBodies/Certification'
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.certification_controller
  /users/independient_user/{user_id}/section:
    post:
      tags:
      - section
      summary: Adds section info to an independient user
      operationId: add_section
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      requestBody:
        $ref: '#/components/requestBodies/Section'
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.section_controller
  /users/organization_user:
    post:
      tags:
      - organization_user
      summary: Register organization user
      operationId: register_organization_user
      requestBody:
        description: Organization user object to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationUser'
        required: true
      responses:
        default:
          description: successful operation
      x-openapi-router-controller: swagger_server.controllers.organization_user_controller
  /users/organization_user/{user_id}:
    get:
      tags:
      - organization_user
      summary: Get user by user id
      operationId: get_organization_user_by_id
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndependientUser'
        "400":
          description: Invalid username supplied
        "401":
          description: Access token is missing or invalid
        "404":
          description: User not found
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.organization_user_controller
    patch:
      tags:
      - organization_user
      summary: Patch organization user
      operationId: patch_organization_user_by_id
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Organization user object to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationUser'
        required: true
      responses:
        default:
          description: successful operation
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.organization_user_controller
  /users/{user_id}/job_offer:
    get:
      tags:
      - job_offer
      summary: Returns a list of job offers published by the user
      description: A list of the job offers published by the user
      operationId: get_job_offers_published_by_the_user
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOffer'
                x-content-type: application/json
        "400":
          description: Invalid status value
        "401":
          description: Access token is missing or invalid
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.job_offer_controller
  /users/{user_id}/job_offer/{job_offer_id}/aplications:
    get:
      tags:
      - job_offer
      - aplications
      summary: Returns a list of aplications in a specified job offer published by
        the user
      description: A list of aplications in the job offer specified published by the
        user
      operationId: get_job_offers_aplications
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      - name: job_offer_id
        in: path
        description: Unique identifier of the job offer
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aplication'
                x-content-type: application/json
        "400":
          description: Invalid status value
        "401":
          description: Access token is missing or invalid
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.job_offer_controller
  /users/{user_id}/job_offers/{job_offer_id}/aplications:
    post:
      tags:
      - job_offer
      - aplications
      summary: Adds an aplication to a specified job offer
      description: Adds an aplication to a specified job offer
      operationId: add_aplication_to_job_offer
      parameters:
      - name: user_id
        in: path
        description: Unique identifier of the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: email
      - name: job_offer_id
        in: path
        description: Unique identifier of the job offer
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.job_offer_controller
  /job_offers:
    get:
      tags:
      - job_offer
      summary: Returns a list of job offers
      description: A list of the last ten job offers published by the others users
      operationId: get_job_offers
      parameters:
      - name: page
        in: query
        description: Pagination
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobOffer'
                x-content-type: application/json
        "400":
          description: Invalid status value
        "401":
          description: Access token is missing or invalid
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.job_offer_controller
    post:
      tags:
      - job_offer
      summary: Add a new job offer to the catalog
      operationId: add_job_offer
      requestBody:
        $ref: '#/components/requestBodies/JobOffer'
      responses:
        "401":
          description: Access token is missing or invalid
        "405":
          description: Invalid input
      security:
      - bearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.job_offer_controller
components:
  schemas:
    Aplication:
      required:
      - aproved
      - date
      type: object
      properties:
        date:
          type: string
          description: Date on which was applied for the job
          format: date
        aproved:
          type: boolean
          description: Flah to know if the aplication was aproved or not
          default: false
        independient_user_id:
          type: number
          description: From who is the aplication
          format: int32
        job_offer_id:
          type: number
          description: Job offer's id
          format: int32
        user_id:
          type: string
          format: string
          description: User's id
      description: Aplication in a job offer from an independient user
      example:
        date: 2000-01-23
        independient_user_id: 134
        job_offer_id: 206
        aproved: false
    Certification:
      required:
      - issuing_company
      - title
      type: object
      properties:
        credential_id:
          type: number
          description: Unique identifier of certification
          format: int32
        credential_url:
          type: string
          description: Certification's url
        issuing_company:
          type: string
          description: Certification issuing company
        expiration_date:
          type: string
          description: Date the certification expires
          format: date
        expedition_date:
          type: string
          description: Date the certification was issued
          format: date
        title:
          type: string
          description: Title of the certification taken
      description: Main structure of a certification object
      example:
        credential_url: credential_url
        expedition_date: 2000-01-23
        issuing_company: issuing_company
        expiration_date: 2000-01-23
        title: title
        credential_id: 521
    Education:
      required:
      - title
      - university
      type: object
      properties:
        education_id:
          type: number
          description: Unique identifier of education
          format: int32
        description:
          type: string
          description: Talk about what the education is about
        discipline:
          type: string
          description: Education's discipline
        end_date:
          type: string
          description: Date where the education finished
          format: date
        start_date:
          type: string
          description: Date where the education started
          format: date
        average:
          type: number
          description: Average obtained upon completion of studies
          format: float
        title:
          type: string
          description: Title of studies taken
        university:
          type: string
          description: University where the education was taken
      description: Main structure of a education object
      example:
        end_date: 2000-01-23
        average: 9.8
        university: university
        education_id: 167
        description: description
        discipline: discipline
        title: title
        start_date: 2000-01-23
    IndependientUser:
      required:
      - name
      type: object
      properties:
        independient_user_id:
          type: number
          description: Unique identifier of the independient user
          format: int32
        surnames:
          pattern: "^[a-zA-Z√Ä-√ø\\u00f1\\u00d1\\s]+$"
          type: string
          description: User' surnames
        name:
          pattern: "^[a-zA-Z√Ä-√ø\\u00f1\\u00d1\\s]+$"
          type: string
          description: User's name
        ocupation:
          pattern: "^[a-zA-Z√Ä-√ø\\u00f1\\u00d1\\s]+$"
          type: string
          description: Actual job
        personal_description:
          type: string
          description: Short description of the user
        user:
          $ref: '#/components/schemas/User'
        education:
          type: array
          description: Education registered by the user
          items:
            $ref: '#/components/schemas/Education'
        laboral_experience:
          type: array
          description: Laboral experiences registered by the user
          items:
            $ref: '#/components/schemas/LaboralExperience'
        certification:
          type: array
          description: Certifications taken by the user
          items:
            $ref: '#/components/schemas/Certification'
        section:
          type: array
          description: Sections published by the user
          items:
            $ref: '#/components/schemas/Section'
      description: Main structure of a independent user
      example:
        ocupation: ocupation
        education:
        - end_date: 2000-01-23
          average: 9.8
          university: university
          education_id: 167
          description: description
          discipline: discipline
          title: title
          start_date: 2000-01-23
        - end_date: 2000-01-23
          average: 8.9
          university: university
          education_id: 169
          description: description
          discipline: discipline
          title: title
          start_date: 2000-01-23
        independient_user_id: 92
        name: name
        personal_description: personal_description
        section:
        - section_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: description
          media:
          - null
          - null
          - null
          - null
          title: title
        - section_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          description: description
          media:
          - null
          - null
          - null
          - null
          title: title
        surnames: surnames
        laboral_experience:
        - end_date: 2000-01-23
          laboral_experience_id: 212
          company_name: company_name
          location: location
          current_job: false
          job_title: job_title
          sector: "AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES"
          job_category: CARPINTERO
          start_date: 2000-01-23
        - end_date: 2000-01-23
          laboral_experience_id: 222
          company_name: company_name
          location: location
          current_job: true
          job_title: job_title
          sector: "AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES"
          job_category: CARPINTERO
          start_date: 2000-01-23
        user:
          country: country
          user_status: active
          password: ""
          profile_photo:
            file: ""
            media_id: 12
          user_id: ""
          city: city
          email: ""
        certification:
        - credential_url: credential_url
          expedition_date: 2000-01-23
          issuing_company: issuing_company
          expiration_date: 2000-01-23
          title: title
          credential_id: 234
        - credential_url: credential_url
          expedition_date: 2000-01-23
          issuing_company: issuing_company
          expiration_date: 2000-01-23
          title: title
          credential_id: 302
    JobOffer:
      required:
      - description
      - job
      type: object
      properties:
        job_offer_id:
          type: number
          description: Unique identifier of the job offer
          format: int32
        job:
          type: string
          description: Title of the job
        description:
          type: string
          description: Talk about what the job offer is about
        job_category:
          $ref: '#/components/schemas/JobCategory'
        location:
          type: string
          description: Location where the job offer is
        media:
          maxItems: 4
          minItems: 0
          type: array
          description: Multimedia data related to the job offer
          items:
            $ref: '#/components/schemas/Media'
        username:
          type: string
          description: User who pusblish the job offer.
      description: Main structure of a job offer
      example:
        description: description
        location: location
        job_offer_id: 206
        media:
        - file: ""
          media_id: 80
        - file: ""
          media_id: 81
        - file: ""
          media_id: 82
        - file: ""
          media_id: 83
        job: job
        job_category: CARPINTERO
        username: username
    JobCategory:
      type: string
      description: Different's categories of job
      enum:
      - CARPINTERO
      - CERRAJERO
      - MECANICO
      - OBRERO
      - FONTANERO
      - SOLDADOR
      - ARTISTA
      - SASTRE
      - AGRIGULTOR
      - COCINERO
      - REPARTIDOR
      - SEGURIDAD
      - ESTILISTA
      - EXTERMINADOR
      - CAMARERO
      - CONDUCTOR
      - ELECTRICISTA
      - FOTOGRAFO
      - CASERO
      - JARDINERO
      - VENDEDOR
      - DENTISTA
      - ENFERMERO
      - DOCTOR
      - EMPRESARIO
      - DEPORTISTA
      - ADMINISTRADOR
      - SECRETARIO
      - SOLDADO
      - CIENTIFICO
      - PROFESOR
      - POLICIA
      - GERENTE
      - BOMBERO
      - INGENIERO
      - ARQUITECTO
      - PERIODISTA
      - BIBLIOTECARIO
      - ABOGADO
      - OTRO
    LaboralExperience:
      required:
      - job_title
      type: object
      properties:
        laboral_experience_id:
          type: number
          description: Unique identifier of the laboral experience
          format: int32
        job_title:
          type: string
          description: Job's title
        current_job:
          type: boolean
          description: A flag to know if this laboral experience is the current job
            of the user
          default: false
        end_date:
          type: string
          description: Date where the laboral experience finished
          format: date
        start_date:
          type: string
          description: Date where the laboral experience started
          format: date
        company_name:
          type: string
          description: Organization's name
        sector:
          $ref: '#/components/schemas/Sector'
        job_category:
          $ref: '#/components/schemas/JobCategory'
        location:
          type: string
          description: Location where the work experience was lived
      description: Structure of a laboral experience object
      example:
        end_date: 2000-01-23
        laboral_experience_id: 212
        company_name: company_name
        location: location
        current_job: false
        job_title: job_title
        sector: "AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES"
        job_category: CARPINTERO
        start_date: 2000-01-23
    Media:
      type: object
      properties:
        media_id:
          type: number
          description: Binary data of the media file
          format: int32
        file:
          type: string
          description: Binary data of the media file
          format: binary
      description: A multimedia file
      example:
        file: ""
        media_id: 80
    OrganizationUser:
      required:
      - contact_email
      - name
      type: object
      properties:
        organization_user_id:
          type: number
          description: Unique identifier of the organization user
          format: int32
        name:
          type: string
          description: Organization's name
        about:
          type: string
          description: Organization overview
        zip_code:
          type: integer
          description: Zip code where the organization is located
          format: int64
        contact_name:
          type: string
          description: Contact person's name
        contact_phone:
          maxLength: 12
          minLength: 5
          type: string
          description: Contact person's phone
          format: phone
        contact_email:
          maxLength: 320
          minLength: 5
          pattern: "\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*"
          type: string
          description: Contact person's email
          format: email
        web_site:
          type: string
          description: Organization's web site
        work_sector:
          $ref: '#/components/schemas/Sector'
        user:
          $ref: '#/components/schemas/User'
      description: Main structure of an organization user object
    Section:
      required:
      - description
      - title
      type: object
      properties:
        section_id:
          type: number
          description: Unique identifier of the section
          format: int32
        title:
          type: string
          description: Title of the section
        description:
          type: string
          description: Main text of the section
        media:
          maxItems: 4
          minItems: 0
          type: array
          description: Multimedia data related to the section
          items:
            $ref: '#/components/schemas/Media'
      description: Personal section that represents a remarkable event or recognition
        by the independent user
      example:
        section_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        description: description
        media:
        - null
        - null
        - null
        - null
        title: title
    Sector:
      type: string
      enum:
      - "AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES"
      - "ALIMENTACION, BEBIDAS, TABACO"
      - COMERCIO
      - CONSTRUCCION
      - EDUCIACION
      - FABRICACION DE MATERIAL DE TRANSPORTE
      - FUNCION PUBLICA
      - "HOTELERIA, RESTAURACI√ìN, TURISMO"
      - INDUSTRIAS QUIMICAS
      - INGENIERIA MECANICA Y ELECTICA
      - "MEDIOS DE COMUNICACION, CULTURA, GRAFICOS"
      - MINERIA
      - "PETROLEO Y PRODUCCION DE GASES, REFINACION DE PETROLEO"
      - PRODUCCION DE MATERIALES BASICOS
      - SERVICIOS DE CORREO Y TELECOMUNICACIONES
      - SERVICIOS DE SALUD
      - "SERVICIOS FINANCIEROS, SERVICIOS PROFESIONALES"
      - SERVICIOS PUBLICOS
      - "SILVICULTURA, MADERA, CELULOSA, PAPEL"
      - "TEXTILES, VESTIDO, CUERO, CALZADO"
      - TRANSPORTE
      - TRANSPORTE MARITIMO
    User:
      required:
      - email
      type: object
      properties:
        user_id:
          type: string
          description: Unique identifier of the user
          format: email
        email:
          maxLength: 320
          minLength: 5
          pattern: "\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*"
          type: string
          description: User's email
          format: email
        password:
          maxLength: 100
          minLength: 8
          type: string
          description: User's password
          format: password
        city:
          pattern: "^[a-zA-Z√Ä-√ø\\u00f1\\u00d1\\s]+$"
          type: string
          description: City where the user lives
        country:
          pattern: "^[a-zA-Z√Ä-√ø\\u00f1\\u00d1\\s]+$"
          type: string
          description: Country where the user lives
        user_status:
          type: string
          description: User status
          default: active
          enum:
          - active
          - inactive
        profile_photo:
          $ref: '#/components/schemas/Media'
      description: "Main structure of an user object, only includes general data"
      example:
        country: country
        user_status: active
        password: ""
        profile_photo:
          file: ""
          media_id: 80
        user_id: ""
        city: city
        email: ""
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  requestBodies:
    Certification:
      description: Certification object that needs to be added to the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Certification'
      required: true
    Education:
      description: Education object that needs to be added to the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Education'
      required: true
    JobOffer:
      description: Job offer object that needs to be added to the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JobOffer'
      required: true
    LaboralExperience:
      description: Laboral experience object that needs to be added to the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LaboralExperience'
      required: true
    Section:
      description: Section object that needs to be added to the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Section'
      required: true
  securitySchemes:
    bearerAuth:
      type: http
      description: This API uses JWT Auth
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_bearerAuth

